// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNg_OBxErfle8jqLApp1B2JE1tebr3DAI',
    appId: '1:993384230410:web:1f6868b55a6b82b77f79f3',
    messagingSenderId: '993384230410',
    projectId: 'med-booking-system',
    authDomain: 'med-booking-system.firebaseapp.com',
    storageBucket: 'med-booking-system.firebasestorage.app',
    measurementId: 'G-GF4HQCBL8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4PU3-ToddNC-bwLN-bBz57PntWREkIMo',
    appId: '1:993384230410:android:62ac7f73cb032acc7f79f3',
    messagingSenderId: '993384230410',
    projectId: 'med-booking-system',
    storageBucket: 'med-booking-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0HN0Qm1icyJHgOLFfsnPh7IyEBZ0QxlU',
    appId: '1:993384230410:ios:875307cf74e793697f79f3',
    messagingSenderId: '993384230410',
    projectId: 'med-booking-system',
    storageBucket: 'med-booking-system.firebasestorage.app',
    iosBundleId: 'com.example.medBookingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0HN0Qm1icyJHgOLFfsnPh7IyEBZ0QxlU',
    appId: '1:993384230410:ios:875307cf74e793697f79f3',
    messagingSenderId: '993384230410',
    projectId: 'med-booking-system',
    storageBucket: 'med-booking-system.firebasestorage.app',
    iosBundleId: 'com.example.medBookingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNg_OBxErfle8jqLApp1B2JE1tebr3DAI',
    appId: '1:993384230410:web:03dbd6dc51ec8eba7f79f3',
    messagingSenderId: '993384230410',
    projectId: 'med-booking-system',
    authDomain: 'med-booking-system.firebaseapp.com',
    storageBucket: 'med-booking-system.firebasestorage.app',
    measurementId: 'G-2DKQ82NHGK',
  );
}
